# Generated by Django 5.1.4 on 2024-12-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('bot_response', models.TextField()),
                ('intent', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('conversation_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_file', models.FileField(upload_to='models/')),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=255)),
                ('accuracy', models.FloatField()),
                ('loss', models.FloatField()),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('model_path', models.CharField(max_length=255)),
            ],
        ),
    ]
