# Generated by Django 5.1.4 on 2024-12-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedmodel',
            name='training_date',
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
